# Generated by Django 3.0.6 on 2021-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('pw', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('preferGenre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.TextField()),
                ('poster_path', models.ImageField(upload_to=None)),
                ('popularity', models.TextField()),
                ('release_date', models.TextField()),
                ('runtime', models.IntegerField()),
                ('vote_average', models.IntegerField()),
                ('overview', models.TextField()),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
